
#define SDP_VERSION           'v'
#define ORIGIN                'o'
#define SESSION_NAME          's'
#define TIMES                 't'
#define MEDIA_ANNOUNCEMENTS   'm'
#define SESSION_AND_MEDIA_INFORMATION  'i'
#define SDP_URI               'u'
#define EMAIL_ADDRESS         'e'
#define PHONE_NUMBER          'p'
#define CONNECTION_DATA       'c'
#define BANDWIDTH             'b'
#define REPEAT_TIMES          'r'
#define ADJUSTMENT_TIME       'z'
#define ENCRYPTION_KEY        'k'
#define ATTRIBUTES            'a' 
